[package]
name = "maddie_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
regex = "1.13.1"
serde_json = "1.0.151"
simple_logger = "5.2.0"
urlencoding = "2.1.3"
uuid = { version =  "1.24.0", features = ["v4"] }
log = "0.4.33"
tiny_http = { version = "0.12.0" , features = ["ssl-openssl"]}
openssl = { version = "0.10", features = ["vendored"] }
serde = { version = "1.0.229", features = ["derive"] }
rand = "0.10.2"
[lints.clippy]
# UM, ACTUALLY
pedantic = { level = "deny", priority = -1 }
# DEVELOPING LINTS
nursery = { level = "deny", priority = -1 }
# DENY PANICS
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
